### ISSUE TITLE
stuck when run client.query(...)

### ISSUE THREAD

**Issue by linweiwei123** [denodrivers/mysql#60]
log shows: NFO connecting 127.0.0.1:3306.
It never callback, stuck forever.  

ENV:
deno: 1.0.0
mysql: 8.0

**Comment by wenjoy** [comment]
Could u post your code also? Currently context doesn't help to narrow down the scope of problem.

**Comment by ajasinski77** [comment]
Hi,
I have a problem with the query function.
After a few selects our software stops working. Query never returns any callback and displays no error.
When querying the database (serverVersion: "5.5.5-10.3.23-MariaDB-0 + deb10u1") with the same selects and when using a database client, eg Worbench, the server always returns the correct value. In this case, it is performed correctly even for more attempts.
I am using Deno 1.2.3. I can't update it due to problems with other packages we are using.
Could this be related to poolSize (connection limit) setting?
What should the standard value be there?
Do you have any ideas on how to fix this problem?

**Comment by ajasinski77** [comment]
I tried on different versions, including the last one (2.5.0) and this problem occurs every time.

The frequency of the problem varies. Sometimes every 10 tries, sometimes every 1000 tries. Unfortunately, every time the API that uses this connection crashes.

**Comment by lideming** [comment]
@ajasinski77 Please try the latest commit I mentioned above.
We have some unreleased fixes since v2.5.0. Hope there is the fix you need.

**Comment by TradeIdeasPhilip** [comment]
I was having similar problems.  I would connect and send a half dozen queries.  The program would often hang forever when I said `await client.query(...)`.  It would hang on different queries for no obvious reasons.  Other times the program would run to the end and exit properly.

When I upgraded to `https://github.com/manyuanrong/deno_mysql/raw/00d4651316a66b7cb7d98625380c98098556a26b/mod.ts` things changed.  All of my queries complete.  However, the program never exits.  It hangs in `function handleTimerMacrotask()` in 11_timers.js.

I'm running multiple `async`s at the same time.  Usually Deno is smart enough to end when the last one finishes.  But not with your latest commit.

**Comment by lideming** [comment]
> All of my queries complete. However, the program never exits. It hangs in `function handleTimerMacrotask()` in 11_timers.js.

A not closed client with idle connections will prevent Deno from automatically exiting, after implementing idle timeout (#81).

In short-running applications, this is a problem.

This is because there are active timers for idle connections. When a connection stayed in the pool for too long, the timer callback will close and remove it. However, after all your tasks finishes, Deno will still wait for these timer.

Unfortunately, I haven't found a solution to this problem. Seems that `setTimeout` and `setInterval` are the only APIs in Deno for the timer and currently there is no way to have Deno not wait for them. 😢

Some workaround in your case: set `idleTimeout` to `1000` (1 second, the default is 4 hours), or close the client manually after queries.
